
version: "2.2"

volumes:

  wp-content_volume:
    name: wp-content_volume
    driver: local
    driver_opts:
      device: /home/akamlah/data/wp-content_volume
      o: bind
      type: none

  wp-database_volume:
    name: wp-database_volume
    driver: local
    driver_opts:
      device: /home/akamlah/data/wp-database_volume
      o: bind
      type: none

networks:
  inception_net:

services:

    php_wordpress:
      build:
        context: ./requirements/php_wp/
        dockerfile: php_wp.dockerfile
      container_name: php_wordpress
      volumes:
        - wp-content_volume:/var/www/akamlah.42.fr/html/
      networks:
        - inception_net
      depends_on:
        - mariadb
      restart: on-failure

    mariadb:
      build:
        context: ./requirements/mariadb/
        dockerfile: mariadb.dockerfile
      container_name: mariadb
      volumes:
        - wp-database_volume:/var/lib/mysql/
      networks:
        - inception_net
      restart: on-failure

    nginx:
      build:
        context: ./requirements/nginx
        dockerfile: nginx.dockerfile
      container_name: nginx
      ports:
        - '443:443'
      volumes:
        - wp-content_volume:/var/www/akamlah.42.fr/html/
      networks:
        - inception_net
      depends_on:
        - php_wordpress
      restart: on-failure
