ARG VERSION=10.12
FROM --platform=amd64 debian:${VERSION}
MAINTAINER akamlah

# install needed packages, set frontend to non-interactive to silence debconf warnings
RUN apt-get update \
	&& DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends --no-install-suggests \
		php7.3 \
		php7.3-cli \
		php7.3-curl \
		php7.3-fpm \
		php7.3-gd \
		php7.3-json \
		php7.3-mbstring \
		php7.3-mysql \
		php7.3-opcache \
		php7.3-xml \
		curl \
		vim \
	&& apt-get remove --purge --auto-remove -y \
	&& rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*;

RUN	mkdir -p /var/www/akamlah.42.fr/html/;

# prerequisite: volume mounted at /var/www/akamlah.42.fr/html/
# /wordpesss directory gets generated by unpacking tar file
RUN	curl -o wordpress.tar.gz -kL "https://wordpress.org/wordpress-6.0.1.tar.gz"; \
	tar -xzf wordpress.tar.gz -C /var/www/akamlah.42.fr/html/; \
	rm wordpress.tar.gz;

# configure wordpress database (provided by mysql container on port 3306)
COPY ./wp-config.php /var/www/akamlah.42.fr/html/wordpress/wp-config.php

# edit www.conf file pf php-fpm service to listen on port 9000 (on which nginx container sends requests for fpm service)
RUN	sed -i 's/listen = \/run\/php\/php7.3-fpm.sock/listen = 9000/g' /etc/php/7.3/fpm/pool.d/www.conf; \
	sed -i 's/;listen.mode = 0660/listen.mode = 0660/g' /etc/php/7.3/fpm/pool.d/www.conf; \
	sed -i 's/;daemonize = yes/daemonize = no/g' /etc/php/7.3/fpm/pool.d/www.conf; \
	sed -i 's/;cgi.fix_pathinfo=1/cgi.fix_pathinfo=0/g' /etc/php/7.3/fpm/php.ini; \
	\
	chown -R www-data:www-data /var/www/akamlah.42.fr/html/;

RUN	service php7.3-fpm start;

# force to stay in foreground, and ignore daemonize option from config file
CMD ["/usr/sbin/php-fpm7.3", "--nodaemonize"]
